M48
; DRILL file {KiCad 7.0.8} date Mon Aug 19 13:22:44 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-19T13:22:44+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.398Y-1.0775
X5.5948Y-1.0775
T2
X5.0Y-0.9055
X5.0Y-3.2283
X6.9291Y-0.9055
X6.9291Y-3.2283
T0
M30
